language: php

php:
  - 7.1

install:
  - composer install

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always

befor_script:
  - ./spec/travis.sh

script:
  -  vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 1f90f153-02db-4f8b-a9c3-60ef9733fc95
